### PR TITLE
Added an option to disable SPA mode

### PR DESCRIPTION
**Pull request by OyewoleOyedeji**
For example:

```ts
export default defineNuxtConfig({
    modules: ["nuxt-electron"]
    electron: {
        disableSPAMode: true
    }
})
```

When `disableSPAMode` is not set the module uses `false`

### CODE REVIEW

**Comment by OyewoleOyedeji** [comment]
I also used Prettier which is a +

**Comment by caoxiemeihao** [comment]
Thanks for this PR! `v0.4.4` support it! 😂

**Comment by OyewoleOyedeji** [comment]
Aight mate, cheers 🍻

**Comment by caoxiemeihao** [comment]
Ah, great to meet you!

**Comment by OyewoleOyedeji** [comment]
hey couid you check, #26

**Pull request closed without merging**
