### PR TITLE
fix: types are missing

### PR DESCRIPTION
**Pull request by so1ve**

### CODE REVIEW

**Review by caoxiemeihao — APPROVED** [review]
LGTM 👍

**Comment by so1ve** [comment]
Let's create a new release? I'm facing this issue now and I have to patch nuxt-electron to make it work 😂

**Comment by caoxiemeihao** [comment]
OK! wait a moment :)

**Comment by caoxiemeihao** [comment]
@so1ve Hey!
v0.6.0 is out 🚀

**Comment by caoxiemeihao** [comment]
I did notice you answering questions in [electron-vite](https://github.com/electron-vite), you're interested in it?

**Comment by so1ve** [comment]
> v0.6.0 is out

Thanks!

> You're interested in it?

Yes I'm using vite-plugin-electron to build electron apps 😂 It's a really good vite plugin!

**Pull request merged**
